[build]
  command = "corepack enable && corepack prepare pnpm@9.15.5 --activate && pnpm --version && pnpm install --frozen-lockfile --reporter=append-only && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_INSTALL = "true"

[[headers]]
  for = "/legacy/js/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/legacy/css/*"
  [headers.values]
    Cache-Control = "no-store"


[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-store"
